/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as HealthRouteImport } from './routes/health'
import { Route as TickerRouteImport } from './routes/$ticker'
import { Route as IndexRouteImport } from './routes/index'

const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerRoute = TickerRouteImport.update({
  id: '/$ticker',
  path: '/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRoute
  '/health': typeof HealthRoute
  '/metrics': typeof MetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRoute
  '/health': typeof HealthRoute
  '/metrics': typeof MetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRoute
  '/health': typeof HealthRoute
  '/metrics': typeof MetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$ticker' | '/health' | '/metrics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$ticker' | '/health' | '/metrics'
  id: '__root__' | '/' | '/$ticker' | '/health' | '/metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TickerRoute: typeof TickerRoute
  HealthRoute: typeof HealthRoute
  MetricsRoute: typeof MetricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$ticker': {
      id: '/$ticker'
      path: '/$ticker'
      fullPath: '/$ticker'
      preLoaderRoute: typeof TickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TickerRoute: TickerRoute,
  HealthRoute: HealthRoute,
  MetricsRoute: MetricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
